"""empty message

Revision ID: 6ea110c1cb30
Revises: ed37ca105d64
Create Date: 2021-02-23 01:06:35.667807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea110c1cb30'
down_revision = 'ed37ca105d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
